package enums;

public enum EventParam {
    FOOD_BONUS,
    FOOD_MALUS,         //ALWAYS POSITIVE. THE MINUS SIGN IS HANDLED INSIDE THE FUNCTIONS
    PRESTIGE_BONUS,
    PRESTIGE_MALUS      //ALWAYS POSITIVE. THE MINUS SIGN IS HANDLED INSIDE THE FUNCTIONS
}
