package enums;

public enum Parameters {
    FOOD_BONUS,
    FOOD_MALUS,         //ALWAYS POSITIVE. THE MINUS SIGN IS HANDLED INSIDE THE FUNCTIONS
    PRESTIGE_BONUS,
    PRESTIGE_MALUS,      //ALWAYS POSITIVE. THE MINUS SIGN IS HANDLED INSIDE THE FUNCTIONS
    ARTIST_NUM           /*ABOVE THIS THRESHOLD, CAVE PAINTINGS GIVES PRESTIGE_BONUS FOR EACH ARTIST
                           BELOW THIS THRESHOLD, CAVE PAINTINGS GIVES PRESTIGE_MALUS */
}
